### ISSUE TITLE
README is missing the required release template in bosh upload

### ISSUE THREAD

**Issue by ashishjain14** [SAP/service-fabrik-blueprint-boshrelease#2]
In https://github.com/SAP/service-fabrik-blueprint-boshrelease#download-and-installation bosh upload should specify a release template.

**Comment by subhankarc** [comment]
Bosh upload release always uploads the latest release if you do not provide the release file name. That is always better as one will not have to search for the latest release. I would prefer that in the readme. In that case readme also does not change even if a new release is created. Please let me know your view.

**Comment by ashishjain14** [comment]
If I do not specify the release it fails for me as per the steps and I see the following

service-fabrik-blueprint-boshrelease$ bosh upload release
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'
The information about latest generated release is missing, please provide release filename

Am I missing something here?

**Comment by ashishjain14** [comment]
I am following the steps as mentioned in this link https://github.com/sap/service-fabrik-blueprint-boshrelease#download-and-installation. Please see the section "Deploy on Bosh-Lite"

**Comment by subhankarc** [comment]
Ah ok. Let me have a look what it does for me. Will get back to you.

**Comment by subhankarc** [comment]
@ashishjain14 I tested it. On lower cli version it is not working. I could not figure out since which version it is working. I guess for now, it is better that we mention the release file name. We need to re-look at it how to make it generic. I feel the following command should work. Can you please have a look and if you feel good about it then update the PR?
```
bosh upload release $(ls -1rv releases/blueprint/blueprint-*.yml | head -1)
```

**Comment by ashishjain14** [comment]
@subhankarc Thanks have made the modifications as suggested.

**Comment by subhankarc** [comment]
Merged the PR https://github.com/SAP/service-fabrik-blueprint-boshrelease/pull/3.

Closing the issue.
